version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/hiko1129/qiicon

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            go get -u golang.org/x/lint/golint

      - run:
          name: lint
          command: |
            golint ./...
            go vet ./...

      - run:
          name: run test
          command: |
            go test ./...

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build