version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/hiko1129/qiicon

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            go get -u golang.org/x/lint/golint 
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            export PATH=$PATH:$GOPATH/bin
            dep ensure

      - run:
          name: lint
          command: |
            go list ./... | xargs -L1 golint -set_exit_status
            go vet ./...

      - run:
          name: run test
          command: |
            go test -cover ./...

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build